# Generated by Django 4.2.1 on 2023-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceSet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='set',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
