# Generated by Django 4.2.1 on 2023-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceSet', '0002_alter_categories_title_alter_set_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='queston',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
