# Generated by Django 4.2.1 on 2023-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceSet', '0005_alter_answers_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='queston',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='uid',
            new_name='id',
        ),
    ]
