# Generated by Django 4.2.1 on 2023-05-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceSet', '0007_maincategory_categories_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queston',
            new_name='Questions',
        ),
    ]
