# Generated by Django 4.2.1 on 2023-05-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_remove_questions_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contest_question', to='contest.contest'),
            preserve_default=False,
        ),
    ]
