# Generated by Django 4.2.1 on 2023-05-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_contestinformation_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contestinformation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contestinformation',
            name='thumbnail',
        ),
    ]
