# Generated by Django 4.2.1 on 2023-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_alter_contestinformation_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='contestinformation',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contest_information', serialize=False, to='contest.contest'),
        ),
    ]
