# Generated by Django 4.2.1 on 2023-05-17 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0012_contestinformation_status_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('result', models.BooleanField(default=0)),
                ('atempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_questin', to='contest.questions')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('select_answser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_answer', to='contest.answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
