# Generated by Django 4.2.1 on 2023-05-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_solvequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='deleted_at',
        ),
        migrations.DeleteModel(
            name='SolveQuestion',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
