# Generated by Django 4.2.1 on 2023-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_remove_subscribe_contest_remove_subscribe_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static\\categories'),
        ),
    ]
