# Generated by Django 4.2.1 on 2023-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_alter_contest_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestinformation',
            name='Top50Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contestinformation',
            name='firstPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contestinformation',
            name='secondPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contestinformation',
            name='thirdPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
